const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const gulp = require('gulp');
const dev = require('./gulp-dev-plugin');

const base = '.';
const jspmCli = path.join(base, 'node_modules', 'jspm', 'jspm.js');
const bundleFlags = ['--skip-source-maps'];

const LAZY_ROUTE_MODULES = [
  'homeComponent',
  'counterComponent',
  'timerComponent',
  'notesComponent',
];

const SHARED_VENDOR = 'angular-core';
const PROD_CORE_BUNDLE = 'dist/core.bundle.js';
const PROD_APP_BUNDLE = 'dist/app.bundle.js';
const PROD_OVERRIDES = 'dist/prod-bundle-overrides.js';

const PROD_MAIN_EXPR = [
  'src/index.js',
  SHARED_VENDOR,
  ...LAZY_ROUTE_MODULES,
].join(' - ');

/** UI-Router 1.x Transition is thenable via .promise; ui-router-extras expects .then on the transition object. */
const UIR_EXTRAS_TRANSITION_NEEDLE =
  'd.transition ? d.transition.then(a, a) : i.sync()';
const UIR_EXTRAS_TRANSITION_REPLACEMENT =
  '(function(){var t=d.transition;return t?e.when(t).then(a,a):i.sync()}())';

function runJspmBundle(expression, outFile) {
  execFileSync(
    process.execPath,
    [jspmCli, 'bundle', expression, outFile, ...bundleFlags],
    { cwd: base, stdio: 'inherit' }
  );
}

function patchBundledUiRouterExtras(bundleAbsPath) {
  let src = fs.readFileSync(bundleAbsPath, 'utf8');
  if (!src.includes(UIR_EXTRAS_TRANSITION_NEEDLE)) {
    throw new Error(
      'gulp prod: expected ui-router-extras futureState transition guard not found in bundle (jspm / extras version drift?)'
    );
  }
  src = src.split(UIR_EXTRAS_TRANSITION_NEEDLE).join(UIR_EXTRAS_TRANSITION_REPLACEMENT);
  fs.writeFileSync(bundleAbsPath, src);
}

function ensureBundleMarker(bundleAbsPath) {
  let src = fs.readFileSync(bundleAbsPath, 'utf8');
  if (!src.startsWith('"bundle";')) {
    src = `"bundle";\n${src}`;
  }
  src = src.split('"format esm";\n').join('');
  fs.writeFileSync(bundleAbsPath, src);
}

function writeProdBundleOverrides() {
  const paths = {};
  const bundles = {};
  const meta = {};
  LAZY_ROUTE_MODULES.forEach((moduleId) => {
    const chunkName = moduleId.replace(/Component$/, '');
    const chunkFile = `dist/${chunkName}.bundle.js`;
    paths[moduleId] = moduleId;
    bundles[chunkFile] = [moduleId];
    meta[chunkFile] = { format: 'register', transpiler: false };
  });

  const file =
    '/* generated by gulp prod — lazy route chunks via SystemJS bundles */\n' +
    `System.config(${JSON.stringify({ paths, bundles, meta })});\n` +
    'System.config({ defaultJSExtensions: false, transpiler: false });\n';
  fs.writeFileSync(path.join(base, PROD_OVERRIDES), file);
}

function buildProdBundles() {
  const distDir = path.join(base, 'dist');
  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  writeProdBundleOverrides();

  runJspmBundle(SHARED_VENDOR, PROD_CORE_BUNDLE);
  runJspmBundle(PROD_MAIN_EXPR, PROD_APP_BUNDLE);

  LAZY_ROUTE_MODULES.forEach((moduleId) => {
    const chunkName = moduleId.replace(/Component$/, '');
    const chunkFile = `dist/${chunkName}.bundle.js`;
    runJspmBundle(`${moduleId} - ${SHARED_VENDOR}`, chunkFile);
    ensureBundleMarker(path.join(base, chunkFile));
  });

  patchBundledUiRouterExtras(path.join(base, PROD_APP_BUNDLE));
}

function devTask() {
  return gulp.src(`${base}/index.html`)
    .pipe(dev(true))
    .pipe(gulp.dest(base));
}

function prodTask() {
  buildProdBundles();

  return new Promise((resolve, reject) => {
    const stream = gulp.src(`${base}/index.html`)
      .pipe(dev(false))
      .pipe(gulp.dest(base));
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

exports.dev = devTask;
exports.prod = prodTask;
exports.default = devTask;
