const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const gulp = require('gulp');
const dev = require('./gulp-dev-plugin');

const base = '.';

const PROD_BUNDLE_EXPR =
  'src/index.js + homeComponent + counterComponent + timerComponent + notesComponent';
const PROD_BUNDLE_OUT = 'dist/app.bundle.js';

/** UI-Router 1.x Transition is thenable via .promise; ui-router-extras expects .then on the transition object. */
const UIR_EXTRAS_TRANSITION_NEEDLE =
  'd.transition ? d.transition.then(a, a) : i.sync()';
const UIR_EXTRAS_TRANSITION_REPLACEMENT =
  '(function(){var t=d.transition;return t?e.when(t).then(a,a):i.sync()}())';
const PROD_OVERRIDES = 'dist/prod-bundle-overrides.js';

const BUNDLE_ROUTE_ALIASES = [
  'homeComponent',
  'counterComponent',
  'timerComponent',
  'notesComponent',
];

function patchBundledUiRouterExtras(bundleAbsPath) {
  let src = fs.readFileSync(bundleAbsPath, 'utf8');
  if (!src.includes(UIR_EXTRAS_TRANSITION_NEEDLE)) {
    throw new Error(
      'gulp prod: expected ui-router-extras futureState transition guard not found in bundle (jspm / extras version drift?)'
    );
  }
  src = src.split(UIR_EXTRAS_TRANSITION_NEEDLE).join(UIR_EXTRAS_TRANSITION_REPLACEMENT);
  fs.writeFileSync(bundleAbsPath, src);
}

function writeProdBundleOverrides() {
  const paths = {};
  const map = {};
  BUNDLE_ROUTE_ALIASES.forEach((id) => {
    paths[id] = id;
    map[id] = id;
  });
  const file =
    '/* generated by gulp prod — bundle route IDs + no in-browser Babel (code is pre-built) */\n' +
    `System.config(${JSON.stringify({ paths, map })});\n` +
    'System.config({ defaultJSExtensions: false, transpiler: false });\n';
  fs.writeFileSync(path.join(base, PROD_OVERRIDES), file);
}

function devTask() {
  return gulp.src(`${base}/index.html`)
    .pipe(dev(true))
    .pipe(gulp.dest(base));
}

function prodTask() {
  const distDir = path.join(base, 'dist');
  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  writeProdBundleOverrides();

  execFileSync(
    process.execPath,
    [
      path.join(base, 'node_modules', 'jspm', 'jspm.js'),
      'bundle',
      PROD_BUNDLE_EXPR,
      PROD_BUNDLE_OUT,
      '--skip-source-maps',
    ],
    { cwd: base, stdio: 'inherit' }
  );

  patchBundledUiRouterExtras(path.join(base, PROD_BUNDLE_OUT));

  return new Promise((resolve, reject) => {
    const stream = gulp.src(`${base}/index.html`)
      .pipe(dev(false))
      .pipe(gulp.dest(base));
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

exports.dev = devTask;
exports.prod = prodTask;
exports.default = devTask;
