#!/usr/bin/env node
/**
 * Smoke tests to verify the project builds and runs correctly.
 * Run with: node scripts/test.js
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const projectRoot = path.join(__dirname, '..');
let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err) {
    console.log(`  ✗ ${name}`);
    console.log(`    ${err.message}`);
    failed++;
  }
}

console.log('\n--- Project smoke tests ---\n');

// Test 1: config.js exists (generated by jspm)
test('config.js exists', () => {
  const configPath = path.join(projectRoot, 'config.js');
  if (!fs.existsSync(configPath)) {
    throw new Error('config.js not found. Run: node node_modules/jspm/jspm.js install -y');
  }
});

// Test 2: jspm_packages exists
test('jspm_packages directory exists', () => {
  const jspmPath = path.join(projectRoot, 'jspm_packages');
  if (!fs.existsSync(jspmPath) || !fs.statSync(jspmPath).isDirectory()) {
    throw new Error('jspm_packages not found. Run: node node_modules/jspm/jspm.js install -y');
  }
});

// Test 3: system.js exists in jspm_packages
test('SystemJS loader exists', () => {
  const systemPath = path.join(projectRoot, 'jspm_packages', 'system.js');
  if (!fs.existsSync(systemPath)) {
    throw new Error('jspm_packages/system.js not found');
  }
});

// Test 4: Source files exist
test('src/index.js exists', () => {
  const indexPath = path.join(projectRoot, 'src', 'index.js');
  if (!fs.existsSync(indexPath)) {
    throw new Error('src/index.js not found');
  }
});

// Test 5: Gulp dev build completes
test('gulp dev build completes', () => {
  execSync('npx gulp dev', {
    cwd: projectRoot,
    stdio: 'pipe'
  });
});

// Test 6: index.html contains dev mode (SystemJS.import)
test('index.html configured for dev mode', () => {
  const htmlPath = path.join(projectRoot, 'index.html');
  const content = fs.readFileSync(htmlPath, 'utf8');
  if (!content.includes('SystemJS.import') || !content.includes('./src/index')) {
    throw new Error('index.html missing SystemJS.import for dev mode');
  }
});

// Test 7: ESLint passes on core source files
test('ESLint passes on core source files', () => {
  execSync('npx eslint "src/index.js" "src/futureRoutes.js" "src/home/home.module.js" --max-warnings 999', {
    cwd: projectRoot,
    stdio: 'pipe'
  });
});

// Test 8: Prod build completes
test('gulp prod build completes', () => {
  execSync('npx gulp prod', {
    cwd: projectRoot,
    stdio: 'pipe',
    timeout: 60000
  });
});

// Test 9: Prod loads SystemJS + single built bundle (no config.js / no per-module jspm fetches)
test('index.html configured for prod after build', () => {
  const htmlPath = path.join(projectRoot, 'index.html');
  const content = fs.readFileSync(htmlPath, 'utf8');
  if (content.includes('system-csp-production.js')) {
    throw new Error('prod must use jspm_packages/system.js');
  }
  if (!content.includes('jspm_packages/system.js')) {
    throw new Error('index.html missing system.js for prod');
  }
  if (!content.includes('dist/app.bundle.js')) {
    throw new Error('index.html missing dist/app.bundle.js for prod');
  }
  if (!content.includes('dist/prod-bundle-overrides.js')) {
    throw new Error('index.html missing dist/prod-bundle-overrides.js for prod');
  }
  const prodBlock = content.split('<!-- !dev -->')[1];
  if (!prodBlock || !prodBlock.split('<!-- /!dev -->')[0]) {
    throw new Error('index.html missing !dev block');
  }
  const prodInner = prodBlock.split('<!-- /!dev -->')[0];
  if (!prodInner.includes('<script src="config.js">')) {
    throw new Error('prod block must load config.js for SystemJS map/paths (overrides disable Babel)');
  }
});

console.log(`\n--- Results: ${passed} passed, ${failed} failed ---\n`);

if (failed > 0) {
  process.exit(1);
}

// Restore dev mode so index.html is ready for development
execSync('node node_modules/gulp/bin/gulp.js dev', {
  cwd: projectRoot,
  stdio: 'pipe'
});
